main:
  project_name: spotify-mlops-final
  experiment_name: dev
  execute_steps:
    - download
    - preprocess
    - check_data
    - segregate
    - decision_tree
    - evaluate
  # This seed will be used to seed the random number generator
  # to ensure repeatibility of the data splits and other
  # pseudo-random operations
  random_seed: 42
data:
  file_url: "https://www.kaggle.com/mrmorj/dataset-of-songs-in-spotify?select=genres_v2.csv"
  reference_dataset: "spotify-mlops-preprocess/data_preprocessed:latest"
  # Threshold for Kolomorov-Smirnov test
  test_size: 0.3
  val_size: 0.3
  # Stratify according to the target when splitting the data
  # in train/test or in train/val
  stratify: genre
decision_tree_pipeline:
  decision_tree:
    criterion: "entropy"
    splitter: "best"
    max_depth: 13
  numerical_pipe:
    model: 0
  export_artifact: "model_export"