wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1644866667
    t:
      3:
      - 16
      4: 3.7.11
      5: 0.12.10
      8:
      - 5
path:
  desc: null
  value: genres_v2.csv
